name: Release assets

on:
  push:
    tags:
      - "*.*.*"

jobs:
  assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 1

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: Build release assets
        run: make release

      - name: Upload release assets
        uses: alexellis/upload-assets@259de5111cb56966d046ced998941e93f91d2c93 # 0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./docker-gen-*.tar.gz"]'

      - name: Cleanup release assets
        run: make dist-clean
